# Generated by Django 6.0.3 on 2026-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0059_alter_gradingperiod_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='sheet_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='scan_sheets/'),
        ),
    ]
