# Generated by Django 6.0.3 on 2026-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0060_alter_scanresult_sheet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='sheet_image',
            field=models.ImageField(blank=True, null=True, upload_to='scan_sheets/'),
        ),
    ]
