# Generated by Django 6.0.3 on 2026-04-06 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0062_alter_scanresult_sheet_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionadmin',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_display', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('ADD', 'Add/Create'), ('EDIT', 'Edit/Update'), ('DELETE', 'Delete')], max_length=10)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
