# Generated by Django 6.0.3 on 2026-04-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0063_institutionadmin_is_first_login_audittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionadmin',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
